### PR TITLE
show plattform changes & delay

### PR DESCRIPTION
**Pull request by FJXHI**
### Changes:
- Platform changes are displayed in red, with the old platform crossed out.
- Delay is displayed:
  - Delay over 5min: Time is shown in red with the delay in minutes "(+x)" following it. A hover text shows the original time.
  - minor delays: Time is shown in orange. A hover text displays the original time and the delay in minutes "(+x)".
  - S-Bahn: Display time in red if delayed by more than 5 minutes.

- Trains are sorted by departure/arrival time (if When=null, then by plannedWhen).
- Cancelled trains are displayed correctly.
- S-Bahn: Cancelled trains are displayed with the planned departure time.
- Fix: Closing Door Gif is not displayed when the train is cancelled.
- Fix in styles.css with missing ":".

- Preparing to Display Train Remarks. (The appearance needs to be improved, therefore the code is only a 

### Ideas for Color Fix line:
- [ ] RE should get its own color or that of IRE.
- [ ] REs from DB Fern (ICE/IC mit Nahverkehrsfreigabe) need maybe a own color. 
- [ ] The Color from the S9 Rhein-Main is to similar to the rail replacement bus

### CODE REVIEW

**Comment by hoolycrash** [comment]
First of all, thank you for the comitted code. Looks great already! 
Showing delays is a great improvement.

There currently is an bug with the `suburban.html` which is constantly redirecting to `departure.html`
Looks like an Copy&Paste Issue here.

- [ ] Fix bug

**Comment by hoolycrash** [comment]
First of all, thank you for the comitted code. Looks great already! 
Showing delays is a great improvement.

There curently is an bug with the `suburban.html` which is constantly redirecting to `departure.html`
Looks like an Copy&Paste Issue here.

- [ ] Fix bug

**Comment by hoolycrash** [comment]
Thank you for your comitted code. 
Looks pretty good, alltough I may change the CSS a little bit later.

Have a nice day!

**Comment by FJXHI** [comment]
Class "tooltip" and "tooltiptext" for hovertext is missing in style.css

image

**Comment by hoolycrash** [comment]
Please delete your Cache in Browsersettings or on Windows simply hit `SHIFT + F5`

**Comment by FJXHI** [comment]
Oh Right, F5 helps.

I'm also still trying to figure out the best way to display the scheduled time, because hovertexts are not useful for mobile devices.

**Comment by hoolycrash** [comment]
The easiest way would probably be:

~~13:05~~
13:26 (+21)

**Pull request merged**
